### ISSUE TITLE
More context-aware cycling

### ISSUE THREAD

**Issue by hkjels** [tarsius/bicycle#12]
If you cycle a document that just have collapsed headers, no table of contents etc, I expect that cycling would toggle expand/collapse of those headers and not try all the other non-existing alternatives. 

Currently it takes three cycles to show all collapsed headings even though there's only one top-level of headings

**Comment by tarsius** [comment]
I don't plan to work on this package again soon, but I am certainly aware that there is room for improvement.

**Comment by tarsius** [comment]
I am closing this because at this point I am not sure anymore I will get around to improve this package before someone else writes something much more powerful based on tree-sitter.
