### ISSUE TITLE
`C-<tab> is undefined`???

### ISSUE THREAD

**Issue by iagogv3** [tarsius/bicycle#14]
Hi!

First of all, thanks for this package. I arrived to it by means of https://github.com/alphapapa/outshine/issues/96#issuecomment-1962965581 to use with Rmarkdown documents.

I have it installed on two computers, the main settings being Emacs 29 on Windows 10 and Emacs 28.2 on Debian (the stable version for the distribution). On Windows it works fine.

In Debian, I have configured the package essentially as you recommend in the README webpage of the repository, just switching `S-tab` with `backtab` (if I check `C-h b` it appears as a synonym of `S-<tab>`):
```
(use-package bicycle
  :after outline
  :bind (:map outline-minor-mode-map
              ([C-tab] . bicycle-cycle)
              ([backtab] . bicycle-cycle-global)))

(require 'prog-mode
(add-hook 'prog-mode-hook 'outline-minor-mode)
(add-hook 'prog-mode-hook 'hs-minor-mode))
```

Then, S-tab works perfectly. However, if I try C-tab, it does not have effect and I get the message `C-<tab> is undefined`. Checking `C-h b` I see
```
C-<tab>                   bicycle-cycle
<backtab>         bicycle-cycle-global
S-<tab>                       <backtab>
```
(and `<backtab> is also present in other lines), but there is no more presence of `C-<tab>`. 

May you help me?

Thanks again!

**Comment by tarsius** [comment]
> ```(require 'prog-mode```

The closing paren is missing.

> ```(add-hook 'prog-mode-hook 'hs-minor-mode))```

One closing paren too many.

**Comment by iagogv3** [comment]
Fixing that does not have any effect on the issue. (thanks anyway)

**Comment by tarsius** [comment]
The mode you use for Rmarkdown likely derives from `text-mode` (not `prog-mode`). It might not derive from that either, I don't know.

To get this working for Rmarkdown specifically, find out what mode is being used and append `-map` to the name of that. That's the map in which you have to add the binding.

**Comment by iagogv3** [comment]
Great, thanks!!!  @tarsius The mode is `gfm-mode`. Now, I do not understand why in the Windows PC worked already, while not in the Debian one. I believe I have essentially the same configuration file, but I will check, mainly if there is something about  `outline-minor-mode`.
