### ISSUE TITLE
cycling doesn't work in emacs lisp buffers

### ISSUE THREAD

**Issue by j-cr** [tarsius/bicycle#5]
When I invoke `bicycle-cycle-global` in an emacs lisp buffer the appropriate message (OVERVIEW, TOC, TREES, ALL) is printed to the minibuffer, but nothing else happens; nothing is folded, no visible changes in the buffer.

When I invoke `bicycle-cycle` on a heading (e.g. `;;; Code:` or `;;; Options`), nothing happens and `FOLDED` is printed to the minibuffer everytime.

Note that `bicycle-cycle` on a code block works (as in `hs-toggle-hiding`), but takes 2 calls instead of one for each new code block; i.e. on the first call nothing happens, only on the second call the code block hides; after that it shows and hides correctly.

Steps to reproduce:
1. Open bicycle.el
2. M-x bicycle-cycle-global

Relevant info:
```
outline-regexp’s value is ";;;\\(;* [^ 	
]\\|###autoload\\)\\|("
Local in buffer bicycle.el; global value is "[*\f]+"
```

    GNU Emacs 25.3.1 (x86_64-suse-linux-gnu, GTK+ Version 3.22.30) of 2019-05-04

**Comment by j-cr** [comment]
Also note that in another buffer (with another lisp-derived major mode) I have `outline-regexp` set to `";;;;* "`:

- `bicycle-cycle` on a heading works correctly
- `bicycle-cycle` on a code block doesn't work and jumps to the heading instead (hs-minor-mode enabled)
-  `bicycle-cycle-global` replaces all the text after the first heading (including the heading itself) with `...` and errors with `outline-back-to-heading: Before first heading` on subsequent calls

**Comment by tarsius** [comment]
Does it work if you bind a key to `bicycle-cycle-global` and press that instead of using `M-x bicycle-cycle-global`? If so, does it also work if you make sure that `M-x` invokes `execute-extended-command` instead of, say, `counsel-M-x`?

The problem seems to be the value of `last-command`. You can add this to the command to observe what is going on: `(message "-- %s %s %s %s" this-command this-original-command last-command real-last-command)`.

**Comment by j-cr** [comment]
Eh, it was my bad - I've added the bindings to another minor mode (modal editing) and didn't realize `outline-minor-mode` wasn't enabled. My bad, sorry. 

Yes, the command is bound to a key (`TAB`).

It works as intended with headings in emacs lisp (standard regexp); I noticed however that on code blocks it behaves weirdly:

1. top-level code blocks are hidden as headings, not as in `hs-toggle-hiding` (due to the standard regexp, not an issue with bicycle per se)
2. with non-top-level code blocks, if point is on the opening paren, the enclosing top-level form is hidden (as a heading) instead; if the point *is moved* after that and `bicycle-cycle` is invoked again, then the top-level form expands and reveals the original form in hidden state; if the point isn't moved however, the top-level form expands and reveals the original form in the non-hidden state. If after that the top-level form is hidden and then un-hidden one more time, the original form always becomes un-hidden too.
3. this-command and this-original command are always `bicycle-cycle`, but the last-command and real-last-command are different sometimes, e.g. `nil [134217834]`; I have translations like "j" -> "M-j" in a minor mode for cursor movement in my config, could that be a problem? EDIT: nope, same behavior with normal (non-translated) bindings: cycle on an inner form, move point, cycle again gives: 
  - `-- bicycle-cycle bicycle-cycle bicycle-cycle bicycle-cycle`
  - `-- bicycle-cycle bicycle-cycle backward-char backward-char`

Also, the behavior with the `";;;;* "` regexp is present with outline-minor-mode enabled, though it's clearly a separate issue; I suspect it might be due to the regexp itself.

I guess this issue can be closed since the original report is a fault on my side; let me know if you want a separate ticket for the weird behavior with non-top-level forms.

**Comment by tarsius** [comment]
I cannot reproduce (2). For it me it always toggles the block that begins on the current line.

Regarding (3): only `last-command` matters. It should be whatever command you invoked last, never `nil`. Key translation should not matter.

You should try to reproduce any issues with an `emacs -Q` first. Also first try a file that does not use a non-standard `outline-regexp`.

**Comment by j-cr** [comment]
(2): with `emacs -Q` I get the same behavior.

Looking at the code, around line 195 after `(hs-hide-block)` there is a call to `(outline-hide-entry)` too, so seems like this behavior is intended(?): when hiding a nested code block, its surrounding top-level form (parsed as a header by the emacs-lisp header regexp) is hidden too; if the point isn't moved by user and cycle is called again, that un-hides the nested code block somehow and expands the heading; if the point is moved, then the nested code block stays hidden.

To clarify, given this code (emacs-lisp buffer, hs on):

```
(defun foo ()
  (bar      ; <-- put the point on the opening paren on this line
   (qux))
  (baz))
```

-- what happens if you put the point at the `bar` paren? For me, it results in:

    (defun foo ()...

-- same as if the point is in the beginning of the line.
EDIT: btw, package version is `20191222.2251`, from melpa.

**Comment by tarsius** [comment]
For me the result is:

```emacs-lisp
(defun foo ()
  (bar      ; <-- put the point on the opening paren on this line...)
  (baz))
```

(Which is slightly weird due to the comment).

**Comment by j-cr** [comment]
Ah, ignore the comment, I've put it just to clarify where the point should be.

For me the result is the same WITH the proposed change (see the pull request), but `(defun foo ()...` without it (on a fresh emacs too). Could it be that your local copy of the package is slightly different?

**Comment by tarsius** [comment]
> Could it be that your local copy of the package is slightly different?

No. (There have been no changes to this library except to comments in over a year.)

But maybe you have some related configuration that I don't have, which is why you should try to reproduce starting from `emacs -Q`.

**Comment by j-cr** [comment]
I did reproduce it on a fresh emacs, and just did it once again to make sure:

- Start with `emacs -Q`
- Copy [this file](https://raw.githubusercontent.com/tarsius/bicycle/master/bicycle.el) into scratch and M-x eval-buffer
- `(global-set-key (kbd "<f6>") 'bicycle-cycle)`
- M-x `outline-minor-mode`
- M-x `hs-minor-mode` 
- Paste the code: 
```
(defun foo ()
  (bar
   (qux))
  (baz))
```
- Put the point at the opening paren at bar: `(bar`
- Press F6
- Expected:
```
(defun foo ()
  (bar...)
  (baz)) 
```
- Actual:
```
(defun foo ()...
```
![Screenshot](https://user-images.githubusercontent.com/41063058/71536675-bb42a780-2933-11ea-99bf-a9b40d9e48a3.png)

**Comment by tarsius** [comment]
I can reproduce now. Previously I could not because I also had `reveal-mode` enabled. Currently looking into if there is any valid reason to do what the code currently does.

**Comment by j-cr** [comment]
Seems like it's this commit: https://github.com/tarsius/bicycle/commit/42a5db3514019d539500a67f913411f5533a1eb3

**Comment by tarsius** [comment]
It's a tiny bit more complex than "it's that commit". See the new commit. :stuck_out_tongue_winking_eye:

**Comment by tarsius** [comment]
Thanks for your help with this.

**Comment by j-cr** [comment]
Yay! Thank you too, and sorry for such a sloppy report on my part. Cheers!
