### ISSUE TITLE
Hiding local block hides end delimiter

### ISSUE THREAD

**Issue by andyleejordan** [tarsius/bicycle#8]
Hi @tarsius,

I just discovered this great package which is making me actually use outline-minor-mode and hideshow!

I think commit 1bd8836171cf8da0be836fc407f2f140f52bdeb1 introduced an unintended side-effect. Given the block:

```elisp
(defgroup bicycle nil
  "Cycle outline and code visibility."
  :group 'hideshow
  :group 'outlines)
```

Using `hs-hide-block` results in:

```elisp
(defgroup bicycle nil...)


```

Where the end delimiter (the paren, in this case) (and the newline, which I understand you were trying to hide) still show up. I noticed something off because the EmacsWiki page on hideshow demonstrated it to act like this.

But using bicycle-cycle as setup in the readme just shows:

```elisp
(defgroup bicycle nil...
```

The newline you were trying to hide is gone, as you intended, but also so is the end delimiter.

Could this behavior be made optional? If I'm hiding blocks locally, I kind of still desire their logical separation to be showed by the end delimiter and newline.

**Comment by tarsius** [comment]
When cycling the visibility of "Options" we get:

1. FOLDED

   ```
   ;;; Options...
   ;;; Commands...
   ```

2. CHILDREN

   ```
   ;;; Options...
   (defgroup bicycle nil...
   (defcustom bicycle-echo-state t...
   ;;; Commands...
   ```

3. SUBTREE

   ```
   ;;; Options
   
   (defgroup bicycle nil
     "Cycle outline and code visibility."
    :group 'hideshow
    :group 'outlines)
   
   (defcustom bicycle-echo-state t
     "Whether to echo the name of the new state while cycling."
     :package-version '(bicycle . "0.1.0")
     :group 'bicycle
     :type 'boolean)
   
   ;;; Commands...
   ```
   
If at the CHILDREN state, we expand just `(defgroup bicycle` and
collapse that again then we used to get:

   ```
   ;;; Options...
   (defgroup bicycle nil...)
   
   (defcustom bicycle-echo-state t...
   ;;; Commands...
   ```
   
You say it was likely unintended that the `)` gets also hidden now,
but it is not, I wanted for it to be possible to put all the children
into the state that we get when the parent enters the CHILDREN state,
*without* having to cycle the parent though the various states again.

I don't think we should add an option to make it possible to restore
the old inconsistency.

**Comment by andyleejordan** [comment]
Hm, perhaps I should just be using `hideshow` and `outline-minor-mode` by themselves for a while and get used to it. `bicycle` seemed like a really nice shortcut to avoid having to learn (and think about) all the different commands of `outline-minor-mode`.

What's your workflow with `bicycle` and hiding just singular codeblocks?

**Comment by tarsius** [comment]
> What's your workflow with `bicycle` and hiding just singular codeblocks?

For top-level forms I just use the cycling command (`C-tab` `bicycle-cycle`).

I don't hide nested code myself. For that you would have to use the `hideshow` commands directly.

**Comment by andyleejordan** [comment]
I've been playing around with this all a lot (and tried `outline-cycle` from `outline-magic` too). Some nice tricks I've applied is to make `TAB` conditionally run the toggle commands using a key binding predicate, like `outline-on-heading-p` or `hs-looking-at-block-start-p`, and I actually have a commit to `bicycle` that makes `bicycle-cycle` (optionally) run `bicycle-cycle-global` when `bobp`, which I found `outline-cycle` does and is really nice! (If you're interested: https://github.com/andschwa/bicycle/commit/635af0dc0a54930b401968a42e0e9bbfd20b108d)

But what I keep running into is in less structured code (like random huge PowerShell scripts I open), I find that `omm` (and things on top of it like both `bicycle-cycle` and `outline-cycle`) just fail to work because there is no top heading. But `hs-hide-level` works pretty well in these cases! What I think I'm missing is more toggle commands for hideshow, and I might end up settling on just using hideshow since it deals better with unstructured code. Oof.

What do you do when `omm` fails to work, or are you strictly using this in supported files?

Anyway, I'll close this and my PR. Thanks for the conversation!

**Comment by tarsius** [comment]
(I've marked this as something to get back to eventually, right now I am a bit busy. :grinning: )
